#!/usr/bin/env python3
"""
Generates prometheus/redfish_targets.yml from a CSV inventory.

Usage:
    python3 generate_targets.py inventory.csv > prometheus/redfish_targets.yml

inventory.csv format (header required):
    ip,vendor,site,gpu,gpu_count
    10.10.5.10,dell,dc1,h200,8
    10.10.5.11,dell,dc1,h200,8
    10.10.6.10,lenovo,dc1,none,0
    ...

gpu_count is the number of physical GPUs in that server. It's carried
through as a target label AND passed to the exporter (via
__param_gpu_count, see prometheus/prometheus.yml) so it can emit an
accurate redfish_gpu_count_configured metric — GPU counts can't be derived
from live Redfish telemetry alone, since some BMC firmware only exposes a
handful of zone/aggregate temperature sensors rather than one per GPU.

Groups rows sharing the same (vendor, site, gpu, gpu_count) into one target
block, which keeps the output compact and keeps Grafana label cardinality
sane.
"""
import csv
import ipaddress
import sys
from collections import defaultdict

def main():
    if len(sys.argv) != 2:
        print("Usage: generate_targets.py inventory.csv", file=sys.stderr)
        sys.exit(1)

    groups = defaultdict(list)

    with open(sys.argv[1], newline="") as f:
        reader = csv.DictReader(f)
        for line_number, row in enumerate(reader, start=2):
            ip = row["ip"].strip()
            # CSV has no comment syntax; accept commented sample rows so they
            # cannot accidentally become Prometheus targets.
            if not ip or ip.startswith("#"):
                continue
            try:
                ipaddress.ip_address(ip)
            except ValueError:
                print(f"Invalid BMC IP at line {line_number}: {ip!r}", file=sys.stderr)
                sys.exit(1)
            key = (row["vendor"].strip(), row["site"].strip(),
                   row.get("gpu", "none").strip(), row.get("gpu_count", "0").strip())
            groups[key].append(ip)

    print("# Auto-generated by generate_targets.py — do not hand-edit.")
    for (vendor, site, gpu, gpu_count), ips in sorted(groups.items()):
        print("\n- targets:")
        for ip in ips:
            print(f"    - '{ip}'")
        print("  labels:")
        print(f"    vendor: {vendor}")
        print(f"    site: {site}")
        print(f"    gpu: {gpu}")
        print(f"    gpu_count: \"{gpu_count}\"")

if __name__ == "__main__":
    main()
