#!/usr/bin/env python3
"""
Generates prometheus/redfish_targets.yml from a CSV inventory.

Usage:
    python3 generate_targets.py inventory.csv > prometheus/redfish_targets.yml

inventory.csv format (header required):
    ip,vendor,site,gpu,gpu_count,hostname
    10.10.5.10,dell,dc1,h200,8,rack1-node1
    10.10.5.11,dell,dc1,h200,8,rack1-node2
    10.10.6.10,lenovo,dc1,none,0,
    ...

gpu_count is the number of physical GPUs in that server. It's carried
through as a target label AND passed to the exporter (via
__param_gpu_count, see prometheus/prometheus.yml) so it can emit an
accurate redfish_gpu_count_configured metric — GPU counts can't be derived
from live Redfish telemetry alone, since some BMC firmware only exposes a
handful of zone/aggregate temperature sensors rather than one per GPU.

hostname is optional and per-host (unlike vendor/site/gpu/gpu_count, which
are typically shared across many rows) — leave it blank for hosts you don't
have a name for. It's attached as a Prometheus target label like the other
inventory fields, so it becomes available as a Grafana variable/filter
without any exporter changes.

Groups rows sharing the same (vendor, site, gpu, gpu_count, hostname) into
one target block. Rows with a distinct hostname each get their own block
(since the key differs); rows with a blank hostname still group together
by the other four fields as before, so a fleet with only a few named hosts
stays compact.
"""
import csv
import ipaddress
import sys
from collections import defaultdict

def main():
    if len(sys.argv) != 2:
        print("Usage: generate_targets.py inventory.csv", file=sys.stderr)
        sys.exit(1)

    groups = defaultdict(list)

    with open(sys.argv[1], newline="") as f:
        reader = csv.DictReader(f)
        for line_number, row in enumerate(reader, start=2):
            ip = row["ip"].strip()
            # CSV has no comment syntax; accept commented sample rows so they
            # cannot accidentally become Prometheus targets.
            if not ip or ip.startswith("#"):
                continue
            try:
                ipaddress.ip_address(ip)
            except ValueError:
                print(f"Invalid BMC IP at line {line_number}: {ip!r}", file=sys.stderr)
                sys.exit(1)
            key = (row["vendor"].strip(), row["site"].strip(),
                   (row.get("gpu") or "none").strip(), (row.get("gpu_count") or "0").strip(),
                   (row.get("hostname") or "").strip())
            groups[key].append(ip)

    print("# Auto-generated by generate_targets.py — do not hand-edit.")
    for (vendor, site, gpu, gpu_count, hostname), ips in sorted(groups.items()):
        print("\n- targets:")
        for ip in ips:
            print(f"    - '{ip}'")
        print("  labels:")
        print(f"    vendor: {vendor}")
        print(f"    site: {site}")
        print(f"    gpu: {gpu}")
        print(f"    gpu_count: \"{gpu_count}\"")
        if hostname:
            print(f"    hostname: {hostname}")

if __name__ == "__main__":
    main()
